name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
<<<<<<< HEAD
        container: cuaesd/aesd-autotest:24-unit-test
=======
        container: cuaesd/aesd-autotest:assignment7
>>>>>>> bf83b44 (Assignment 7 source)
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
<<<<<<< HEAD
        container: cuaesd/aesd-autotest:24-assignment7
=======
<<<<<<< HEAD
        container: cuaesd/aesd-autotest:24-assignment6
=======
        container: cuaesd/aesd-autotest:assignment7
>>>>>>> bf83b44 (Assignment 7 source)
>>>>>>> 3de9b65 (added oops analysis)
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
